#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XWeather.Droid.Resource", IsApplication=true)]

namespace XWeather.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::XWeather.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::XWeather.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::XWeather.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::XWeather.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::XWeather.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::XWeather.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::XWeather.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::XWeather.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::XWeather.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::XWeather.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::XWeather.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::XWeather.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::XWeather.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::XWeather.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::XWeather.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::XWeather.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::XWeather.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::XWeather.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::XWeather.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::XWeather.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::XWeather.Droid.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::XWeather.Droid.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::XWeather.Droid.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::XWeather.Droid.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::XWeather.Droid.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::XWeather.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::XWeather.Droid.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::XWeather.Droid.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::XWeather.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::XWeather.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::XWeather.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::XWeather.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::XWeather.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::XWeather.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::XWeather.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::XWeather.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::XWeather.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::XWeather.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::XWeather.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::XWeather.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::XWeather.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::XWeather.Droid.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::XWeather.Droid.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::XWeather.Droid.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::XWeather.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::XWeather.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::XWeather.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::XWeather.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::XWeather.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int MvxBind = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int MvxDropDownItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int MvxGroupItemTemplate = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int MvxItemTemplate = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int MvxLang = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int MvxSource = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int MvxTemplate = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int MvxTemplateSelector = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int CloudyGray = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int PartlyCloudyBlue = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int SunnyBlue = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ConditionHumidity = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ConditionWind = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Sunrise = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Sunset = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int CurrentTemperature = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int DetectedCity = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int ForecastList = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int HumidityPanel = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int LoadingLayout = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int MainContainer = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int MvvmCrossTagId = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MvxBindingTagUnique = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int SunrisePanel = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int SunsetPanel = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int WeatherDescription = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int WindPanel = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int forecastitem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771979};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
